"""The algorithm chart generator.

docs/dx7_algorithms.svg is not committed: docs/conf.py redraws it from
src/msfa/fm_core.cc at the start of every docs build, so it cannot go stale.
What is worth pinning is that the generator still produces a complete chart and
still offers conf.py the entry point it calls.
"""

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
TOOL = ROOT / "docs" / "make_algorithm_chart.py"
SOURCE = ROOT / "src" / "msfa" / "fm_core.cc"


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_generator_produces_a_complete_chart(tmp_path):
    regenerated = tmp_path / "chart.svg"
    subprocess.run(
        [sys.executable, str(TOOL), "-o", str(regenerated)],
        check=True, capture_output=True,
    )
    svg = regenerated.read_text(encoding="utf-8")

    assert svg.startswith('<?xml version="1.0" encoding="UTF-8"?>')
    assert "<!-- Generated by docs/make_algorithm_chart.py" in svg
    assert svg.rstrip().endswith("</svg>")
    numbers = sorted(int(n) for n in re.findall(r'class="alg-num"[^>]*>(\d+)<', svg))
    assert numbers == list(range(1, 33))


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_conf_py_can_draw_the_chart():
    """docs/conf.py calls render_chart() at builder-inited; keep that contract."""
    tool = _tool()
    svg = tool.render_chart()
    assert svg.startswith('<?xml version="1.0" encoding="UTF-8"?>')
    assert "<svg" in svg
    assert svg.count('class="alg-num"') == 32


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_chart_generation_is_deterministic(tmp_path):
    outputs = []
    for i in range(2):
        path = tmp_path / f"chart{i}.svg"
        subprocess.run(
            [sys.executable, str(TOOL), "-o", str(path)],
            check=True, capture_output=True,
        )
        outputs.append(path.read_text(encoding="utf-8"))
    assert outputs[0] == outputs[1]


def _tool():
    """Import the generator, which lives outside the package."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("make_algorithm_chart", TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_feedback_never_collides_with_modulation_wiring():
    """The feedback loop must find a clear route in every algorithm.

    Algorithm 15 is the one that needs it: operator 2's loop used to leave the
    right-hand side straight through the rail carrying operators 5 and 6 into
    operator 4. The router now tries the other side when a side is blocked.
    """
    tool = _tool()
    algorithms = tool.parse_algorithms(SOURCE)
    assert len(algorithms) == 32

    for alg in algorithms:
        geometry = tool.panel_geometry(alg)
        feedback = geometry["feedback"]
        assert feedback is not None, f"algorithm {alg['number']} has no feedback"

        obstacles = geometry["wires"] + geometry["arrows"]
        clashes = [
            (segment, obstacle)
            for segment in feedback["segments"]
            for obstacle in obstacles
            if tool._overlap(segment, obstacle)
        ]
        assert not clashes, (
            f"algorithm {alg['number']}: feedback crosses modulation wiring "
            f"at {clashes[0]}"
        )


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_feedback_arrives_pointing_down_at_the_centre_of_its_target():
    """Including algorithms 4 and 6, whose loop wraps a whole chain.

    Those two used to stop at the side of the operator that receives the
    feedback, so they read differently from every other algorithm.
    """
    tool = _tool()
    for alg in tool.parse_algorithms(SOURCE):
        geometry = tool.panel_geometry(alg)
        points = geometry["feedback"]["points"]
        (x_before, y_before), (x_end, y_end) = points[-2], points[-1]

        assert x_before == pytest.approx(x_end), (
            f"algorithm {alg['number']}: feedback does not end with a vertical run"
        )
        assert y_end > y_before, (
            f"algorithm {alg['number']}: feedback does not end pointing down"
        )

        target_x, target_y = geometry["box_xy"](alg["fb_in"])
        assert x_end == pytest.approx(target_x + tool.BOX_W / 2), (
            f"algorithm {alg['number']}: feedback is not horizontally centred"
        )
        assert y_end == pytest.approx(target_y), (
            f"algorithm {alg['number']}: feedback does not land on the box top"
        )


@pytest.mark.skipif(not TOOL.exists(), reason="chart generator not shipped (installed package)")
def test_no_operator_both_receives_feedback_and_is_modulated():
    """Why centring the feedback arrow cannot collide with a modulation arrow."""
    tool = _tool()
    for alg in tool.parse_algorithms(SOURCE):
        modulated = {target for _, target in alg["edges"]}
        assert alg["fb_in"] not in modulated, (
            f"algorithm {alg['number']}: operator {alg['fb_in']} takes both "
            f"feedback and modulation into its top edge"
        )
